-- TODO: CRIAR DOCUMETOVEICULO / AJUSTAR VEICULO 
-- 		 DEFAULT SYSDATE EM VEZ DE TRIGGER
--╔═══════════════╗--
--║ TABELA ESTADO ║--
--╚═══════════════╝--
CREATE TABLE ESTADO 
(
  ID NUMBER NOT NULL 
, NOME VARCHAR2(20) NOT NULL 
, UF VARCHAR2(2) NOT NULL 
, CODIGOIBGE VARCHAR2(2) NOT NULL 
, DATAINCLUSAO DATE NOT NULL 
, DATAALTERACAO DATE 
, STATUS NUMBER(1,0) DEFAULT 1 NOT NULL 
, CONSTRAINT ESTADO_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE OR REPLACE TRIGGER INSERT_ESTADO
BEFORE INSERT ON ESTADO
FOR EACH ROW
BEGIN
  SELECT SYSDATE INTO :NEW.DATAINCLUSAO FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER UPDATE_ESTADO
BEFORE UPDATE ON ESTADO
FOR EACH ROW
BEGIN
  SELECT SYSDATE INTO :NEW.DATAALTERACAO FROM DUAL;
END;
/
--╔══════════════════╗--
--║ TABELA MUNICIPIO ║--
--╚══════════════════╝--
CREATE TABLE MUNICIPIO 
(
  ID NUMBER NOT NULL
, NOME VARCHAR2(40) NOT NULL 
, CODIGOIBGE VARCHAR2(7) NOT NULL 
, ESTADOID NUMBER NOT NULL 
, DATAINCLUSAO DATE NOT NULL 
, DATAALTERACAO DATE 
, STATUS NUMBER(1,0) DEFAULT 1 NOT NULL 
, CONSTRAINT MUNICIPIO_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE MUNICIPIO
ADD CONSTRAINT MUNICIPIO_FK_ESTADO FOREIGN KEY
(
  ESTADOID 
)
REFERENCES ESTADO
(
  ID 
)
ENABLE;

CREATE SEQUENCE SEQ_MUNICIPIOID
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER GERA_MUNICIPIOID
BEFORE INSERT ON MUNICIPIO
FOR EACH ROW
BEGIN
  SELECT SEQ_MUNICIPIOID.NEXTVAL INTO :NEW.ID FROM DUAL;
END; 
/
CREATE OR REPLACE TRIGGER INSERT_MUNICIPIO
BEFORE INSERT ON MUNICIPIO
FOR EACH ROW
BEGIN
  SELECT SYSDATE INTO :NEW.DATAINCLUSAO FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER UPDATE_MUNICIPIO
BEFORE UPDATE ON MUNICIPIO
FOR EACH ROW
BEGIN
  SELECT SYSDATE INTO :NEW.DATAALTERACAO FROM DUAL;
END;
/
--╔═════════════════╗--
--║ TABELA ENDERECO ║--
--╚═════════════════╝--
CREATE TABLE ENDERECO 
(
  ID NUMBER NOT NULL 
, LOGRADOURO VARCHAR2(100) NOT NULL 
, NUMERO NUMBER 
, COMPLEMENTO VARCHAR2(20) 
, CEP VARCHAR2(9) NOT NULL 
, BAIRRO VARCHAR(50)
, MUNICIPIOID NUMBER NOT NULL 
, DATAINCLUSAO DATE NOT NULL 
, DATAALTERACAO DATE 
, STATUS NUMBER(1,0) DEFAULT 1 NOT NULL 
, CONSTRAINT ENDERECO_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE ENDERECO
ADD CONSTRAINT ENDERECO_FK_MUNICIPIO FOREIGN KEY
(
  MUNICIPIOID 
)
REFERENCES MUNICIPIO
(
  ID 
)
ENABLE;

CREATE SEQUENCE SEQ_ENDERECOID
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER GERA_ENDERECOID
BEFORE INSERT ON ENDERECO
FOR EACH ROW
BEGIN
  SELECT SEQ_ENDERECOID.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER INSERT_ENDERECO
BEFORE INSERT ON ENDERECO
FOR EACH ROW
BEGIN
  SELECT SYSDATE INTO :NEW.DATAINCLUSAO FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER UPDATE_ENDERECO
BEFORE UPDATE ON ENDERECO
FOR EACH ROW
BEGIN
  SELECT SYSDATE INTO :NEW.DATAALTERACAO FROM DUAL;
END;
/
--╔═════════════════════╗--
--║ TABELA CATEGORIACNH ║--
--╚═════════════════════╝--
CREATE TABLE CATEGORIACNH 
(
  ID NUMBER NOT NULL
, CATEGORIA VARCHAR2(3) NOT NULL 
, DATAINCLUSAO DATE DEFAULT SYSDATE NOT NULL 
, DATAALTERACAO DATE 
, STATUS NUMBER(1,0) DEFAULT 1 NOT NULL
, CONSTRAINT CATEGORIACNH_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE OR REPLACE TRIGGER UPDATE_CATEGORIACNH
BEFORE UPDATE ON CATEGORIACNH
FOR EACH ROW
BEGIN
  SELECT SYSDATE INTO :NEW.DATAALTERACAO FROM DUAL;
END;
/
--╔════════════╗--
--║ TABELA CNH ║--
--╚════════════╝--
CREATE TABLE CNH 
(
  ID NUMBER NOT NULL  
, NUMERO VARCHAR2(11) NOT NULL  
, RENACH VARCHAR2(11) NOT NULL 
, ESPELHO VARCHAR2(10) NOT NULL 
, DATAEMISSAO DATE NOT NULL 
, DATAVALIDADE DATE NOT NULL 
, CATEGORIAID NUMBER NOT NULL 
, DATAINCLUSAO DATE DEFAULT SYSDATE NOT NULL 
, DATAALTERACAO DATE 
, STATUS NUMBER(1,0) DEFAULT 1 NOT NULL
, CONSTRAINT CNH_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
, CONSTRAINT CNH_FK_CATEGORIA FOREIGN KEY 
  (
    CATEGORIAID 
  ) REFERENCES CATEGORIACNH (ID)
  ENABLE 
, CONSTRAINT CNH_UK_NUMERO UNIQUE 
  (
    NUMERO 
  )
  ENABLE
, CONSTRAINT CNH_PK_RENACH UNIQUE 
  (
    RENACH 
  )
  ENABLE
, CONSTRAINT CNH_PK_ESPELHO UNIQUE 
  (
    ESPELHO 
  )
  ENABLE
);

CREATE SEQUENCE SEQ_CNHID
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER GERA_CNHID
BEFORE INSERT ON CNH
FOR EACH ROW
BEGIN
  SELECT SEQ_CNHID.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER UPDATE_CNH
BEFORE UPDATE ON CNH
FOR EACH ROW
BEGIN
  SELECT SYSDATE INTO :NEW.DATAALTERACAO FROM DUAL;
END;
/
--╔══════════════════╗--
--║ TABELA MOTORISTA ║--
--╚══════════════════╝--
CREATE TABLE MOTORISTA 
(
  ID NUMBER NOT NULL 
, PRIMEIRONOME VARCHAR2(50) NOT NULL 
, SOBRENOME VARCHAR2(50) NOT NULL 
, CPF VARCHAR2(15) NOT NULL
, RG VARCHAR2(12) NOT NULL
, DATANASCIMENTO DATE NOT NULL 
, CNHID NUMBER NOT NULL
, ENDERECOID NUMBER NOT NULL 
, DATAINCLUSAO DATE NOT NULL 
, DATAALTERACAO DATE
, STATUS NUMBER(1,0) DEFAULT 1 NOT NULL 
, CONSTRAINT MOTORISTA_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
, CONSTRAINT MOTORISTA_FK_CNH FOREIGN KEY 
  (
    CNHID 
  ) REFERENCES CNH
  (
	ID
  )
  ENABLE 
, CONSTRAINT MOTORISTA_UK_CNHID UNIQUE 
  (
    CNHID 
  )
  ENABLE
);

ALTER TABLE MOTORISTA
ADD CONSTRAINT MOTORISTA_FK_ENDERECO FOREIGN KEY
(
  ENDERECOID 
)
REFERENCES ENDERECO
(
  ID 
)
ENABLE;

ALTER TABLE MOTORISTA
ADD CONSTRAINT MOTORISTA_UK_CPF UNIQUE 
(
  CPF
)
ENABLE;

CREATE SEQUENCE SEQ_MOTORISTAID
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER GERA_MOTORISTAID
BEFORE INSERT ON MOTORISTA
FOR EACH ROW
BEGIN
  SELECT SEQ_MOTORISTAID.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER INSERT_MOTORISTA
BEFORE INSERT ON MOTORISTA
FOR EACH ROW
BEGIN
  SELECT SYSDATE INTO :NEW.DATAINCLUSAO FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER UPDATE_MOTORISTA
BEFORE UPDATE ON MOTORISTA
FOR EACH ROW
BEGIN
  SELECT SYSDATE INTO :NEW.DATAALTERACAO FROM DUAL;
END;
/
--╔═════════════════════╗--
--║ TABELA MARCAVEICULO ║--
--╚═════════════════════╝--
CREATE TABLE MARCAVEICULO 
(
  ID NUMBER NOT NULL 
, NOME VARCHAR2(20) NOT NULL 
, DATAINCLUSAO DATE NOT NULL 
, DATAALTERACAO DATE 
, STATUS NUMBER(1,0) DEFAULT 1 NOT NULL 
, CONSTRAINT MARCAVEICULO_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE SEQUENCE SEQ_MARCAID
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER GERA_MARCAID
BEFORE INSERT ON MARCAVEICULO
FOR EACH ROW
BEGIN
  SELECT SEQ_MARCAID.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER INSERT_MARCA
BEFORE INSERT ON MARCAVEICULO
FOR EACH ROW
BEGIN
  SELECT SYSDATE INTO :NEW.DATAINCLUSAO FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER UPDATE_MARCA
BEFORE UPDATE ON MARCAVEICULO
FOR EACH ROW
BEGIN
  SELECT SYSDATE INTO :NEW.DATAALTERACAO FROM DUAL;
END;
/
--╔══════════════════════╗--
--║ TABELA MODELOVEICULO ║--
--╚══════════════════════╝--
CREATE TABLE MODELOVEICULO 
(
  ID NUMBER NOT NULL 
, NOME VARCHAR2(20) NOT NULL
, DATAINCLUSAO DATE NOT NULL 
, DATAALTERACAO DATE 
, STATUS NUMBER(1,0) DEFAULT 1 NOT NULL 
, CONSTRAINT MODELOVEICULO_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE SEQUENCE SEQ_MODELOID
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER GERA_MODELOID
BEFORE INSERT ON MODELOVEICULO
FOR EACH ROW
BEGIN
  SELECT SEQ_MODELOID.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER INSERT_MODELO
BEFORE INSERT ON MODELOVEICULO
FOR EACH ROW
BEGIN
  SELECT SYSDATE INTO :NEW.DATAINCLUSAO FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER UPDATE_MODELO
BEFORE UPDATE ON MODELOVEICULO
FOR EACH ROW
BEGIN
  SELECT SYSDATE INTO :NEW.DATAALTERACAO FROM DUAL;
END;
/
--╔════════════════════╗--
--║ TABELA TIPOVEICULO ║--
--╚════════════════════╝--
CREATE TABLE TIPOVEICULO 
(
  ID NUMBER NOT NULL 
, DESCRICAO VARCHAR2(20) NOT NULL 
, DATAINCLUSAO DATE NOT NULL 
, DATAALTERACAO DATE 
, STATUS NUMBER(1,0) DEFAULT 1 NOT NULL 
, CONSTRAINT TIPOVEICULO_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
); 

CREATE SEQUENCE SEQ_TIPOVEICULOID
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER GERA_TIPOVEICULOID
BEFORE INSERT ON TIPOVEICULO
FOR EACH ROW
BEGIN
  SELECT SEQ_TIPOVEICULOID.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER INSERT_TIPOVEICULO
BEFORE INSERT ON TIPOVEICULO
FOR EACH ROW
BEGIN
  SELECT SYSDATE INTO :NEW.DATAINCLUSAO FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER UPDATE_TIPOVEICULO
BEFORE UPDATE ON TIPOVEICULO
FOR EACH ROW
BEGIN
  SELECT SYSDATE INTO :NEW.DATAALTERACAO FROM DUAL;
END;
/
--╔════════════════╗--
--║ TABELA VEICULO ║--
--╚════════════════╝--
CREATE TABLE VEICULO 
(
  ID NUMBER NOT NULL 
, PLACA VARCHAR2(8) NOT NULL 
, MARCAVEICULOID NUMBER NOT NULL 
, MODELOVEICULOID NUMBER NOT NULL 
, TIPOVEICULOID NUMBER NOT NULL 
, DATAINCLUSAO DATE NOT NULL 
, DATAALTERACAO DATE 
, STATUS NUMBER(1,0) DEFAULT 1 NOT NULL 
, CONSTRAINT VEICULO_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE VEICULO
ADD CONSTRAINT VEICULO_FK_TIPOVEICULO FOREIGN KEY
(
  TIPOVEICULOID 
)
REFERENCES TIPOVEICULO
(
  ID 
)
ENABLE;

ALTER TABLE VEICULO
ADD CONSTRAINT VEICULO_FK_MARCA FOREIGN KEY
(
  MARCAVEICULOID 
)
REFERENCES MARCAVEICULO
(
  ID 
)
ENABLE;

ALTER TABLE VEICULO
ADD CONSTRAINT VEICULO_FK_MODELO FOREIGN KEY
(
  MODELOVEICULOID 
)
REFERENCES MODELOVEICULO
(
  ID 
)
ENABLE;

ALTER TABLE VEICULO
ADD CONSTRAINT VEICULO_UK_PLACA UNIQUE 
(
  PLACA
)
ENABLE;

CREATE SEQUENCE SEQ_VEICULOID
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER GERA_VEICULOID
BEFORE INSERT ON VEICULO
FOR EACH ROW
BEGIN
  SELECT SEQ_VEICULOID.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER INSERT_VEICULO
BEFORE INSERT ON VEICULO
FOR EACH ROW
BEGIN
  SELECT SYSDATE INTO :NEW.DATAINCLUSAO FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER UPDATE_VEICULO
BEFORE UPDATE ON VEICULO
FOR EACH ROW
BEGIN
  SELECT SYSDATE INTO :NEW.DATAALTERACAO FROM DUAL;
END;
/
--╔══════════════════════════╗--
--║ TABELA MOTORISTA_VEICULO ║--
--╚══════════════════════════╝--
CREATE TABLE MOTORISTA_VEICULO 
(
  ID NUMBER NOT NULL 
, MOTORISTAID NUMBER NOT NULL 
, VEICULOID NUMBER NOT NULL 
, DATAINCLUSAO DATE NOT NULL 
, DATAALTERACAO DATE 
, STATUS NUMBER(1,0) DEFAULT 1 NOT NULL
, CONSTRAINT MOTORISTA_VEICULO_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE MOTORISTA_VEICULO
ADD CONSTRAINT MOTORISTAVEICULO_FK_MOTORISTA FOREIGN KEY
(
  MOTORISTAID 
)
REFERENCES MOTORISTA
(
  ID 
)
ENABLE;

ALTER TABLE MOTORISTA_VEICULO
ADD CONSTRAINT MOTORISTAVEICULO_FK_VEICULO FOREIGN KEY
(
  VEICULOID 
)
REFERENCES VEICULO
(
  ID 
)
ENABLE;

CREATE SEQUENCE SEQ_MOTORISTA_VEICULOID
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER GERA_MOTORISTA_VEICULOID
BEFORE INSERT ON MOTORISTA_VEICULO
FOR EACH ROW
BEGIN
  SELECT SEQ_MOTORISTA_VEICULOID.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER INSERT_MOTORISTA_VEICULO
BEFORE INSERT ON MOTORISTA_VEICULO
FOR EACH ROW
BEGIN
  SELECT SYSDATE INTO :NEW.DATAINCLUSAO FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER UPDATE_MOTORISTA_VEICULO
BEFORE UPDATE ON MOTORISTA_VEICULO
FOR EACH ROW
BEGIN
  SELECT SYSDATE INTO :NEW.DATAALTERACAO FROM DUAL;
END;
/
--╔═════════════════════╗--
--║ TABELA MOTIVOVIAGEM ║--
--╚═════════════════════╝--
CREATE TABLE MOTIVOVIAGEM 
(
  ID NUMBER NOT NULL
, DESCRICAO VARCHAR2(50) NOT NULL  
, DATAINCLUSAO DATE DEFAULT SYSDATE NOT NULL 
, DATAALTERACAO DATE 
, STATUS NUMBER(1,0) DEFAULT 1 NOT NULL
, CONSTRAINT MOTIVOVIAGEM_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE
 );
--╔═════════════════════╗--
--║ TABELA STATUSVIAGEM ║--
--╚═════════════════════╝--
CREATE TABLE STATUSVIAGEM 
(
  ID NUMBER NOT NULL
, DESCRICAO VARCHAR2(50) NOT NULL  
, DATAINCLUSAO DATE DEFAULT SYSDATE NOT NULL 
, DATAALTERACAO DATE 
, STATUS NUMBER(1,0) DEFAULT 1 NOT NULL
, CONSTRAINT STATUSVIAGEM_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE
 );
--╔═══════════════╗--
--║ TABELA VIAGEM ║--
--╚═══════════════╝--
CREATE TABLE VIAGEM 
(
  ID NUMBER NOT NULL
, CODIGO VARCHAR2(20) NOT NULL  
, MOTORISTAID NUMBER NOT NULL 
, VEICULOID NUMBER NOT NULL 
, INICIO DATE NOT NULL
, FIM DATE
, MOTIVOID NUMBER NOT NULL
, STATUSVIAGEMID NUMBER NOT NULL
, DATAINCLUSAO DATE DEFAULT SYSDATE NOT NULL 
, DATAALTERACAO DATE 
, STATUS NUMBER(1,0) DEFAULT 1 NOT NULL
, CONSTRAINT VIAGEM_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE
, CONSTRAINT VIAGEM_FK_MOTORISTA FOREIGN KEY 
  (
    MOTORISTAID 
  ) REFERENCES MOTORISTA
  (
	ID
  )
  ENABLE
, CONSTRAINT VIAGEM_FK_VEICULO FOREIGN KEY 
  (
    VEICULOID 
  ) REFERENCES VEICULO
  (
	ID
  )
  ENABLE
, CONSTRAINT VIAGEM_FK_MOTIVO FOREIGN KEY 
  (
    MOTIVOID 
  ) REFERENCES MOTIVOVIAGEM
  (
	ID
  )
  ENABLE
, CONSTRAINT VIAGEM_FK_STATUS FOREIGN KEY 
  (
    STATUSVIAGEMID
  ) REFERENCES STATUSVIAGEM
  (
	ID
  )
  ENABLE
, CONSTRAINT VIAGEM_UK_CODIGO UNIQUE
  (
	CODIGO
  )
);

CREATE SEQUENCE SEQ_VIAGEMID
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER GERA_VIAGEMID
BEFORE INSERT ON VIAGEM
FOR EACH ROW
BEGIN
  SELECT SEQ_VIAGEMID.NEXTVAL INTO :NEW.ID FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER UPDATE_VIAGEM
BEFORE UPDATE ON VIAGEM
FOR EACH ROW
BEGIN
  SELECT SYSDATE INTO :NEW.DATAALTERACAO FROM DUAL;
END;
/